In [34]:
# TODO: Add import statements
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso, LinearRegression
from sklearn.preprocessing import StandardScaler

In [37]:
# Assign the data to predictor and outcome variables
# TODO: Load the data
train_data = pd.read_csv('data-regularization.csv', header = None)
# is this the same as: 
# X = train_data.iloc[:,:-1]
# y = train_data.iloc[:,-1]
X = train_data.iloc[:,:6]
y = train_data.iloc[:,6]
print(X)
print(y)

           0        1         2        3        4        5
0    1.25664  2.04978  -6.23640  4.71926 -4.26931  0.20590
1   -3.89012 -0.37511   6.14979  4.94585 -3.57844  0.00640
2    5.09784  0.98120  -0.29939  5.85805  0.28297 -0.20626
3    0.39034 -3.06861  -5.63488  6.43941  0.39256 -0.07084
4    5.84727 -0.15922  11.41246  7.52165  1.69886  0.29022
..       ...      ...       ...      ...      ...      ...
95  -4.58240 -1.27825   7.55098  8.83930 -3.80318  0.04386
96 -10.00364  2.66002  -4.26776 -3.73792 -0.72349 -0.24617
97  -4.32624 -2.30314  -8.16044  4.46366 -3.33569 -0.01655
98  -1.90167 -0.15858 -10.43466  4.89762 -0.64606 -0.14519
99   2.43213  2.41613   2.49949 -8.03891 -1.64164 -0.63444

[100 rows x 6 columns]
0     12.31798
1     23.67628
2     -1.53459
3    -24.68670
4     17.54122
        ...   
95    26.14768
96     0.76214
97   -10.05262
98   -19.63970
99    12.76193
Name: 6, Length: 100, dtype: float64


In [48]:
# TODO: Create the linear regression model with lasso regularization.
scaler = StandardScaler()
scaler.fit(X)

X_scaled = scaler.transform(X)

lasso_reg = Lasso()
linear_reg = LinearRegression()

# TODO: Fit the model.
lasso_reg.fit(X, y)
linear_reg.fit(X,y)

# TODO: Retrieve and print out the coefficients from the regression model. the columns with coef 0 are useless features
#If we use a normal linear regression we would see the base coefficients before regularization
reg_coef = lasso_reg.coef_
reg_coef

array([ 0.        ,  2.35793224,  2.00441646, -0.05511954, -3.92808318,
        0.        ])

In [49]:
linear_reg.coef_

array([-6.19918532e-03,  2.96325160e+00,  1.98199191e+00, -7.86249920e-02,
       -3.95818772e+00,  9.30786141e+00])

In [52]:
## impact now using feature scaling
lasso_reg.fit(X_scaled, y)
linear_reg.fit(X_scaled, y)
reg_coef = lasso_reg.coef_
reg_coef

array([  0.        ,   3.90753617,   9.02575748,  -0.        ,
       -11.78303187,   0.45340137])

In [51]:
linear_reg.coef_

array([ -0.03429525,   5.12341093,   9.8249303 ,  -0.63866951,
       -12.53990789,   1.69699858])